export const colors = {
  // ── NEW DESIGN SYSTEM TOKENS ──
  primary: '#2563EB',
  primaryDark: '#1D4ED8',
  primaryLight: '#DBEAFE',
  secondary: '#475569',
  secondaryLight: '#F1F5F9',
  background: '#F8FAFC',
  surface: '#FFFFFF',
  textPrimary: '#0F172A',
  textSecondary: '#64748B',
  textMuted: '#94A3B8',
  border: '#E2E8F0',
  borderDark: '#CBD5E1',
  success: '#16A34A',
  successLight: '#DCFCE7',
  warning: '#D97706',
  warningLight: '#FEF3C7',
  danger: '#DC2626',
  dangerLight: '#FEE2E2',
  info: '#0284C7',
  infoLight: '#E0F2FE',

  // ── LEGACY ALIASES (backward compat) ──
  text: '#0F172A',
  muted: '#94A3B8',
  mutedBackground: '#F1F5F9',
  primaryForeground: '#FFFFFF',
  secondaryForeground: '#FFFFFF',
  dangerForeground: '#FFFFFF',
};
