import { z } from 'zod';
declare const configSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "production", "test"]>>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["error", "warn", "info", "http", "verbose", "debug", "silly"]>>;
    DATABASE_URL: z.ZodString;
    JWT_SECRET: z.ZodString;
    JWT_ACCESS_EXPIRY: z.ZodDefault<z.ZodString>;
    JWT_REFRESH_EXPIRY: z.ZodDefault<z.ZodString>;
    STORAGE_PROVIDER: z.ZodDefault<z.ZodEnum<["local", "supabase", "s3"]>>;
    STORAGE_BUCKET: z.ZodDefault<z.ZodString>;
    STORAGE_LOCAL_PATH: z.ZodDefault<z.ZodString>;
    SUPABASE_URL: z.ZodOptional<z.ZodString>;
    SUPABASE_SERVICE_ROLE_KEY: z.ZodOptional<z.ZodString>;
    RATE_LIMIT_TTL: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    RATE_LIMIT_MAX: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    ARGON2_MEMORY_COST: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    ARGON2_TIME_COST: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
    ARGON2_PARALLELISM: z.ZodDefault<z.ZodEffects<z.ZodString, number, string>>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "production" | "test";
    LOG_LEVEL: "error" | "warn" | "info" | "http" | "verbose" | "debug" | "silly";
    DATABASE_URL: string;
    JWT_SECRET: string;
    JWT_ACCESS_EXPIRY: string;
    JWT_REFRESH_EXPIRY: string;
    STORAGE_PROVIDER: "local" | "supabase" | "s3";
    STORAGE_BUCKET: string;
    STORAGE_LOCAL_PATH: string;
    RATE_LIMIT_TTL: number;
    RATE_LIMIT_MAX: number;
    ARGON2_MEMORY_COST: number;
    ARGON2_TIME_COST: number;
    ARGON2_PARALLELISM: number;
    SUPABASE_URL?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
}, {
    DATABASE_URL: string;
    JWT_SECRET: string;
    NODE_ENV?: "development" | "production" | "test" | undefined;
    LOG_LEVEL?: "error" | "warn" | "info" | "http" | "verbose" | "debug" | "silly" | undefined;
    JWT_ACCESS_EXPIRY?: string | undefined;
    JWT_REFRESH_EXPIRY?: string | undefined;
    STORAGE_PROVIDER?: "local" | "supabase" | "s3" | undefined;
    STORAGE_BUCKET?: string | undefined;
    STORAGE_LOCAL_PATH?: string | undefined;
    SUPABASE_URL?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
    RATE_LIMIT_TTL?: string | undefined;
    RATE_LIMIT_MAX?: string | undefined;
    ARGON2_MEMORY_COST?: string | undefined;
    ARGON2_TIME_COST?: string | undefined;
    ARGON2_PARALLELISM?: string | undefined;
}>;
export type Config = z.infer<typeof configSchema>;
export declare function loadConfig(env?: NodeJS.ProcessEnv): Config;
export declare const config: {
    NODE_ENV: "development" | "production" | "test";
    LOG_LEVEL: "error" | "warn" | "info" | "http" | "verbose" | "debug" | "silly";
    DATABASE_URL: string;
    JWT_SECRET: string;
    JWT_ACCESS_EXPIRY: string;
    JWT_REFRESH_EXPIRY: string;
    STORAGE_PROVIDER: "local" | "supabase" | "s3";
    STORAGE_BUCKET: string;
    STORAGE_LOCAL_PATH: string;
    RATE_LIMIT_TTL: number;
    RATE_LIMIT_MAX: number;
    ARGON2_MEMORY_COST: number;
    ARGON2_TIME_COST: number;
    ARGON2_PARALLELISM: number;
    SUPABASE_URL?: string | undefined;
    SUPABASE_SERVICE_ROLE_KEY?: string | undefined;
};
export {};
//# sourceMappingURL=index.d.ts.map